### PR TITLE
SeattleColleges.github.io_6_10_collect_student_info

### LINKED ISSUE #10: Data - Collect Student Info: Collect student info & create JSON file
**Tasks**
Collect the following from each student:
- [x] Photo that represents student
- [x] Role taken in practicum
- [ ] About me blurb
- [x] Email
- [x] Github link
- [ ] Linkedin link

Other tasks:
- [x] Create a JSON file with this info
- [x] Add student images to images folder

### PR DESCRIPTION
**Pull request by heosman**
Resolves #10 

This PR adds an `images` folder and a `students.json` file in the `src` folder. Currently, there is a placeholder profile image and a several student photos in the images folder. I added all students (according to the Notion Team directory), but some of them have info which are empty. 24 students in the student.json file have complete information at the moment.

Related to #9

### CODE REVIEW

**Comment by nickolasram** [comment]
Thanks for working on this 🙏 it seems like tedious work

**Review by brinkbrink — APPROVED** [review]
Feel free to merge without requirements if you want to add the missing blurbs/pictures in a separate PR request.

**Comment by el-riber** [comment]
that looks great!

**Review by intisarosman1 — APPROVED** [review]
Looks good! Great work

**Pull request merged**
