### PR TITLE
SeattleColleges.github.io_8_52_Footer_Component_Integration

### PR DESCRIPTION
**Pull request by BradleyCharles**
- Resolves Issue #52

This Pull Request is to add the Footer component to the remaining pages of the Practicum website. I waited until the portfolio page was merged into main so that I could include it as one of the pages that have a footer.

Screenshot 2024-06-12 125531
Screenshot 2024-06-12 125540
Screenshot 2024-06-12 125546
Screenshot 2024-06-12 125553
Screenshot 2024-06-12 125600

### CODE REVIEW

**Comment by Diego-Cano** [comment]
Hey Bradley,

I checked out the changes you made to add the footer into the Contact, Main, and Portfolio pages. The updates look great, and I appreciate the effort to match the footer's background with the navbar—it helps with the visual consistency. I noticed that you adjusted the footer position to fix broken links and updated the footer background, which is great attention to detail.

I checked all of the links you added and they worked as intended. I like how you added the Tree Frog logo at the bottom. The UI looks more professional thanks to your work.

Screenshot 2024-06-11 at 4 42 07 PM

Also, I found a good article on [Responsive Layout Setup (Header, Content, Footer) for React Apps](https://mahdi-karimipour.medium.com/responsive-layout-setup-header-content-footer-for-your-react-single-page-application-spa-f5287cdf2a50)

**Comment by BradleyCharles** [comment]
Thank you @Diego-Cano! I am always looking for ways to improve my design so I appreciate the article that you provided, I hope it will help me make my pages more responsive.

**Review by el-riber — COMMENTED** [review]
I can be wrong but when i try to test it says have a probelm with the imports.. this is what show me 
Screenshot 2024-06-12 at 9 55 27 PM

when i belive i fix the import i can not see the footer:
Screenshot 2024-06-12 at 9 58 09 PM

Always have the chance i am doing something wrong.. but this import is a problem when i will test : import { FormComponent } from "../components/microComponents/contact/form";

I think inside the file microComponents do not have contact or form. bur when i fix the import it still does not show. I think I am doing something wrong
Screenshot 2024-06-12 at 9 34 45 PM

**Review by JesseCaddell — APPROVED** [review]
Lookin good Brad! This really ties the whole page together. Everything is working on my end as well.
image

**Review by Asfand00 — APPROVED** [review]
Looks Great, the site is coming along nicely, this is just one image of the homepage but I am seeing the footer implemented on each tab, nice work!
Footer2

**Review by Alzavio — APPROVED** [review]

**Pull request merged**
