### PR TITLE
SeattleColleges.github.io_8_56_Portfolio_Page_(Content)

### PR DESCRIPTION
**Pull request by Alzavio**
Resolves 56

Adds the content to the portfolio page for our other projects, adds a the footer to the portfolio page, and a few miscellaneous bugs
image

### CODE REVIEW

**Review by nickolasram — APPROVED** [review]
Everything looks great! And thanks for remembering to include the footer!

**Review by IsaacJrTypes — APPROVED** [review]
LGTM. Good work!

**Review by intisarosman1 — APPROVED** [review]
Very neat and composed! LGTM

Screenshot 2024-06-12 011725
Screenshot 2024-06-12 011737

**Review by heosman — APPROVED** [review]
LGTM, but branch conflicts need to be resolved.

image

**Pull request merged**
