### PR TITLE
SeattleColleges.github.io_7_15_Implement Design: Style navbar 

### PR DESCRIPTION
**Pull request by Alzavio**
Resolves: 15
Description: Makes the navbar design match Figma
image

### CODE REVIEW

**Review by BradleyCharles — APPROVED** [review]
Navbar looks great and is functional. Great job!

Screenshot 2024-05-23 124606
Screenshot 2024-05-23 124632

**Review by nickolasram — APPROVED** [review]
Approved, but merging is blocked due to an unsigned commit

**Comment by nickolasram** [comment]
@brinkbrink can you merge this into main manually? There's just an unsigned commit holding it up

**Review by Asfand00 — APPROVED** [review]
LGTM
navbar_practicum
Since the commit is unsigned merging is blocked still, I can try to help troubleshoot if you need it.

**Pull request merged**
